### ISSUE TITLE
`apt-cache show` fails on package that does exist (`libtk8.6`)

### ISSUE THREAD

**Issue by bruno-digitbio** [awalsh128/cache-apt-pkgs-action#106]
Package validation is [currently done](https://github.com/awalsh128/cache-apt-pkgs-action/blob/1850ee53f6e706525805321a3f2f863dcf73c962/pre_cache_action.sh#L59) by using `apt-cache show ${package}`. However, on the latest version of the GitHub actions runner for Ubuntu, some packages (e.g., `libtk8.6`) are not visible to `apt-cache` until after an `apt-get update`.

This means that `cache-apt-pkgs-action` errors our during validation even though the package *would* successfully install after an `apt-fast update`.

Minimal reproducible example:
```yaml
jobs:
  example-broken-job:
    name: example-broken-job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Fetch the current and previous commits.
          fetch-depth: 2
          submodules: 'recursive'
      - name: Install apt dependencies for Bazel bootstrapping
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libtk8.6
          version: 1.0
```

To reproduce the issue directly in a runner:
```
$ docker attach $(docker run --name github-actions-ubuntu-2 -d -i -t catthehacker/ubuntu:act-latest /bin/bash)
root@e6d223c9b85a:/tmp# apt-cache show libtk8.6
N: Unable to locate package libtk8.6
N: Couldn't find any package by glob 'libtk8.6'
N: Couldn't find any package by regex 'libtk8.6'
E: No packages found
root@e6d223c9b85a:/tmp# apt-get install libtk8.6
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libtk8.6
E: Couldn't find any package by glob 'libtk8.6'
E: Couldn't find any package by regex 'libtk8.6'
root@e6d223c9b85a:/tmp# apt-get update
<SNIP>
root@e6d223c9b85a:/tmp# apt-cache show libtk8.6
Package: libtk8.6
Architecture: amd64
Version: 8.6.12-1build1
Multi-Arch: same
Priority: optional
Section: libs
Source: tk8.6
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Tcl/Tk Packagers <pkg-tcltk-devel@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 2367
Provides: libtk
Depends: libtcl8.6 (>= 8.6.0-2), libc6 (>= 2.35), libfontconfig1 (>= 2.12.6), libx11-6, libxft2 (>> 2.1.1), libxss1
Suggests: tk8.6
Conflicts: libtk-img (<< 1.2.5), tk40 (<= 4.0p3-2), tk8.6 (<< 8.6.0-2)
Replaces: tk8.6 (<< 8.6.0-2)
Filename: pool/main/t/tk8.6/libtk8.6_8.6.12-1build1_amd64.deb
Size: 783834
MD5sum: 0b77eaf674cddbcf4be3ae5daf33a5da
SHA1: e915a51f975e2c9f9f06105500dd346f939edc73
SHA256: fd394fe34bce405d66079518f122917e434dc269315ed4125dc982d31a03684d
SHA512: ab375b502a641ee170f940fd8775aa0fc1033f5c499886bcc8d9fb06b3bf5da2cd53cc8de6b96abec898215b8de70ec741c2bfad3ae9af4a94d4647988efc064
Homepage: http://www.tcl.tk/
Description: Tk toolkit for Tcl and X11 v8.6 - run-time files
Description-md5: 01d90661559e5ce16fbf055f91aff291
Task: ubuntustudio-desktop
```
