### ISSUE TITLE
Matrix multi-arch build scenario not supported

### ISSUE THREAD

**Issue by thehedgefrog** [awalsh128/cache-apt-pkgs-action#134]
I have an action that does multi-architecture builds.  While your action has no issues with the common dependencies, any try to install architecture-specific deps in the action results in failed builds as they can't find the packages.

Here is the current snippet:
```
      - name: Setup dependencies
        run: |
          sudo dpkg --add-architecture armhf
          sudo dpkg --add-architecture arm64
          echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse" | sudo tee /etc/apt/sources.list
          echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
          echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu jammy-security main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
          echo "deb [arch=armhf,arm64] http://ports.ubuntu.com/ubuntu-ports jammy main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
          echo "deb [arch=armhf,arm64] http://ports.ubuntu.com/ubuntu-ports jammy-updates main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
          echo "deb [arch=armhf,arm64] http://ports.ubuntu.com/ubuntu-ports jammy-security main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
          sudo apt-get update

      - name: Install common dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1.4.2
        with:
          packages: gcc g++ cmake make libasio-dev libncurses-dev libssl-dev

      - name: Install dependencies
        run: |
          if [ "${{ matrix.arch }}" == "arm64" ]; then
            sudo apt-get install -y g++-aarch64-linux-gnu gcc-aarch64-linux-gnu libasio-dev:arm64 libncurses-dev:arm64 libssl-dev:arm64
          elif [ "${{ matrix.arch }}" == "arm" ] || [ "${{ matrix.arch }}" == "armhf" ]; then
            sudo apt-get install -y g++-arm-linux-gnueabihf gcc-arm-linux-gnueabihf libasio-dev:armhf libncurses-dev:armhf libssl-dev:armhf
          fi
```

Any try to leverage conditional runs of the action for `arm64`, `arm` or `armhf` packages run fine, but the build never succeeds.

As far as I have been able to find, this isn't related to the non-file dependencies limitation.  Am I running into a different limitation?

**Comment by torsknod2** [comment]
@thehedgefrog Without having tested it, why can't you do something like: `packages: gcc g++ cmake make libasio-dev libncurses-dev libssl-dev ${{matrix.arch == "arm64" && "g++-aarch64-linux-gnu gcc-aarch64-linux-gnu libasio-dev:arm64 libncurses-dev:arm64 libssl-dev:arm64" || ""}} ${{(matrix.arch == "arm" || matrix.arch == "armhf") && "g++-arm-linux-gnueabihf gcc-arm-linux-gnueabihf libasio-dev:armhf libncurses-dev:armhf libssl-dev:armhf" || ""}}`

I guess it shares the cache independent of the matrix variable and this causes you problem.
If yes, please try something like `version: ${{matrix.arch}}`.

For the case it's not working, what warnings and/ or errors do you get?

**Comment by awalsh128** [comment]
@thehedgefrog could you verify this?

**Comment by spencercjh** [comment]
I had a similar problem and I used it to install musl-tools, martrix makes 2 different arch amd64 and arm64, and I found out that the content of musl-gcc is incorrect for arm64, it is still the amd64 version.

It's a hack trick from chaos-mesh:

```yaml
  go:
    timeout-minutes: 30
    needs: changes
    if: ${{ needs.changes.outputs.go == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        arch: [ amd64, arm64 ]
        job:
          - verify
          - build
    runs-on: ${{ fromJson('{"amd64":"ubuntu-24.04", "arm64":"ubuntu-24.04-arm"}')[matrix.arch] }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v5.3.0
        with:
          go-version: '1.24'
          check-latest: true
      - name: Cache APT Packages
        uses: awalsh128/cache-apt-pkgs-action@v1.4.3
        with:
          packages: musl-tools
          execute_install_scripts: true
      - name: what's wrong with the musl?
        run: |
          cat /usr/bin/musl-gcc
```
