### ISSUE TITLE
Symlinks not correctly set on Ubuntu 24.04

### ISSUE THREAD

**Issue by pdfrod** [awalsh128/cache-apt-pkgs-action#156]
I'm having issues with the package `ffmpegthumbnailer` on Ubuntu 24.04. When the package and its dependencies are freshly installed things go well, but when the packages are restored from cache, I get the following error when trying to run `ffmpegthumbnailer`:
```
ffmpegthumbnailer: error while loading shared libraries: libblas.so.3: cannot open shared object file: No such file or directory
```

So it seems that that some symlinks are missing. On Ubuntu 22.04 things work perfectly, so something might have changed on Ubuntu 24.04.

I was able to workaround the issue by running:

```
sudo update-alternatives --install \
  /usr/lib/x86_64-linux-gnu/libblas.so.3 \
  libblas.so.3-x86_64-linux-gnu \
  /usr/lib/x86_64-linux-gnu/blas/libblas.so.3 \
  10

sudo update-alternatives --install \
  /usr/lib/x86_64-linux-gnu/liblapack.so.3 \
  liblapack.so.3-x86_64-linux-gnu \
  /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3 \
  10
```

Here is an example configuration file that exposes the issue:

```yaml
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: awalsh128/cache-apt-pkgs-action@v1.5.0
        with:
          packages: ffmpegthumbnailer
          version: 1
          execute_install_scripts: true

      - name: Test ffmpegthumbnailer
        run: ffmpegthumbnailer
```

**Comment by awalsh128** [comment]
@pdfrod any updates?

**Comment by pdfrod** [comment]
Hi @awalsh128. Unfortunately it's still not working for me.

I tested with the [example configuration](https://github.com/awalsh128/cache-apt-pkgs-action/issues/156#issue-2976597017) I mentioned above using both the latest master and https://github.com/awalsh128/cache-apt-pkgs-action/commit/9f7a885e33ff6f8166b600e3e74a981ec11b92c3, and both gave me the same error:

> ffmpegthumbnailer: error while loading shared libraries: libblas.so.3: cannot open shared object file: No such file or directory

**Comment by immoseb** [comment]
I confirm that this issue persists with `v1.6.0`.

**Comment by aliberts** [comment]
I hit the same issue on our CI with `libblas3` and `liblapack3` on `ubuntu-latest` (24.04.4 LTS). After investigating the root cause, I found two distinct problems with cache restore:

1. **`update-alternatives` symlinks aren't cached.** Packages like `libblas3` and `liblapack3` use `update-alternatives` to create their `.so.3` symlinks (e.g., `/usr/lib/x86_64-linux-gnu/libblas.so.3` → `blas/libblas.so.3`). These symlinks aren't owned by the package — `dpkg -L` doesn't list them — so they're not included in the tar. `execute_install_scripts: true` doesn't help either, because these packages rely on dpkg triggers rather than per-package `postinst` scripts.

2. **`ldconfig` is never run on restore.** Even when `.so` files are correctly restored to disk, the dynamic linker cache (`ld.so.cache`) is stale. This causes `dlopen` failures for any shared library loaded at runtime (in our case, FFmpeg libs needed by torchcodec: `libavutil.so.58: cannot open shared object file`).

My workaround is a generic fixup step after the cache action:

```yaml
- uses: awalsh128/cache-apt-pkgs-action@v1.6.0
  with:
    packages: ffmpeg libblas3 ...

- name: Fix cached library registration
  run: |
    # Recreate update-alternatives symlinks for BLAS/LAPACK
    for dir in blas lapack; do
      for lib in /usr/lib/x86_64-linux-gnu/$dir/*.so.*; do
        [ -f "$lib" ] && sudo ln -sf "$lib" /usr/lib/x86_64-linux-gnu/$(basename "$lib")
      done
    done
    # Refresh the dynamic linker cache
    sudo ldconfig
```

This is more generic than hardcoding `update-alternatives --install` calls — it handles any current and future libraries in the `blas/` and `lapack/` subdirectories without knowing the specific alternative names.

Note: the `ldconfig` issue affects any package that provides shared libraries (not just BLAS/LAPACK). If you use this action with packages like `ffmpeg`, `libgl1`, etc., you likely need the `sudo ldconfig` line too.
