### ISSUE TITLE
libvips package not recognized as valid input by cache-apt-pkgs-action

### ISSUE THREAD

**Issue by rmzoni** [awalsh128/cache-apt-pkgs-action#158]
## Title

`libvips` package not recognized as valid input by `cache-apt-pkgs-action`

## Describe the bug

When using the [`awalsh128/cache-apt-pkgs-action`](https://github.com/awalsh128/cache-apt-pkgs-action) to cache `libvips`, the action fails with the following error:

Even though `libvips` is specified in the `packages` input, it appears to be resolved as an empty string during execution.

## Workflow Snippet

```yaml
- name: Cache libvips
  uses: awalsh128/cache-apt-pkgs-action@latest
  with:
    packages: libvips
    version: 1.1
    execute_install_scripts: true
```
## Logs / Error
PACKAGES: libvips
```
Validating action arguments (version='1.1', packages='')...
aborted
Packages argument cannot be empty.
```

###  Full log
```
Run awalsh128/cache-apt-pkgs-action@latest
  with:
    packages: libvips
    version: 1.1
    execute_install_scripts: true
    debug: false
  env:
    GROUPS_COMMA: 1,[2](https://github.com/GenialCare/core/actions/runs/14411253570/job/40419478646#step:6:2),3
    GROUPS_UNDERSCORE: 1_2_[3](https://github.com/GenialCare/core/actions/runs/14411253570/job/40419478646#step:6:3)
    DISABLE_SPRING: 1
    RAILS_ENV: test
    DATABASE_USERNAME: postgres
    DATABASE_PASSWORD: postgres
    PARALLEL_TEST_PROCESSORS: 3
    FIRESTORE_EMULATOR_HOST: localhost:8081
    SPEC_OPTS: --tag ~js
Run ${GITHUB_ACTION_PATH}/pre_cache_action.sh \
  ${GITHUB_ACTION_PATH}/pre_cache_action.sh \
    ~/cache-apt-pkgs \
    "$VERSION" \
    "$EXEC_INSTALL_SCRIPTS" \
    "$DEBUG" \
    "$PACKAGES"
  echo "CACHE_KEY=$(cat ~/cache-apt-pkgs/cache_key.md5)" >> $GITHUB_ENV
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GROUPS_COMMA: 1,2,3
    GROUPS_UNDERSCORE: 1_2_3
    DISABLE_SPRING: 1
    RAILS_ENV: test
    DATABASE_USERNAME: postgres
    DATABASE_PASSWORD: postgres
    PARALLEL_TEST_PROCESSORS: 3
    FIRESTORE_EMULATOR_HOST: localhost:8081
    SPEC_OPTS: --tag ~js
    VERSION: 1.1
    EXEC_INSTALL_SCRIPTS: true
    DEBUG: false
    PACKAGES: libvips
20:12:58.168 Normalizing package list...
20:12:58.332 done
20:12:58.336 Validating action arguments (version='1.1', packages='')...
20:12:58.339 aborted
20:12:58.3[4](https://github.com/GenialCare/core/actions/runs/14411253570/job/40419478646#step:6:4)1 Packages argument cannot be empty.
```

**Comment by chaadow** [comment]
+1

**Comment by brendon** [comment]
It's pretty weird but you can use `libvips-dev` instead and that seems to do the job.

**Comment by DeltaLaboratory** [comment]
still happening with package libvips-dev

**Comment by BenDeJonge** [comment]
I am facing the same empty package list issue with:

```yaml
      - name: Install graphical dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libegl1-mesa-dev libxkbcommon-x11-0 libfontconfig1
          version: 1.0
```
