### ISSUE TITLE
Cache symlinks for pkgs

### ISSUE THREAD

**Issue by pablgonz** [awalsh128/cache-apt-pkgs-action#25]
Hi, I am trying to capture `ghostscript` and almost everything is going perfect, with the only detail of a symbolic link that is not restored from the cache.

I run the solution manually (no problem), but it would be great if this didn't happen. As an example I have this test repo [cache-apt-gs](https://github.com/pablgonzTemp/cache-apt-gs).

With the following configuration file:

```yml
name: Test cache-ghostscript

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  using-apt-fast:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Update sources and install ghostscript
        run: >
         sudo apt-fast -y update < /dev/null > /dev/null && sudo apt-fast -y install --no-install-recommends ghostscript < /dev/null > /dev/null

         gsicclink=/usr/share/ghostscript/$(gs --version)/iccprofiles

         if readlink -e "$gsicclink"; then
            echo $gsicclink is a symlink
         else
            echo $gsicclink is not a symlink
         fi

  cache-apt-pkgs:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Update sources and install ghostscript
        uses: awalsh128/cache-apt-pkgs-action@v1.0.2
        with:
          packages: fonts-urw-base35 libgs9-common libijs-0.35 libjbig2dec0 libopenjp2-7 libgs9 ghostscript
          version: 1.0
          refresh: true
      # libgs9-common creates a symlink from /usr/share/ghostscript, but silently fails to create
      - run: >
         gsicclink=/usr/share/ghostscript/$(gs --version)/iccprofiles

         if readlink -e "$gsicclink"; then
            echo $gsicclink is a symlink
         else
            echo $gsicclink is not a symlink
         fi
```

get for `using-apt-fast:`

```
/usr/share/ghostscript/9.50/iccprofiles is a symlink
```

get for `cache-apt-pkgs:`

```
/usr/share/ghostscript/9.50/iccprofiles is not a symlink
```

Thanks for the great work
Regards

**Comment by awalsh128** [comment]
Hey @pablgonz, it looks like this is from `libgs9-common` and the problem is that I only pipe regular files to the tar.

```sh
dpkg -L "libgs9-common" |
while IFS= read -r f; do     
  if test -f $f; then echo "${f:1}"; fi;
done | 
xargs tar -czf "/tmp/test.tar" -C /
```

Updating the conditional to consider symlinks with `if test -f $f || test -L $f; then echo "${f:1}"; fi;` fixes it though. Going to do an update and pull into master. Then going to have you try the action `@master` to make sure it resolves your issue (staging is currently broken).

**Comment by awalsh128** [comment]
All set @pablgonz. Update the action to use master instead of the version and let me know if it works. I'll add a regression test for this later and do a patch rev 1.0.3.

**Comment by pablgonz** [comment]
@awalsh128 Hello, thanks for the prompt response, now it has worked, of course I had to modify:

```yml
      - name: Update sources and install ghostscript
        uses: awalsh128/cache-apt-pkgs-action@master
        with:
          packages: fonts-urw-base35 libgs9-common libijs-0.35 libjbig2dec0 libopenjp2-7 libgs9 ghostscript
          version: 3.0
          refresh: true
```

That is, I had to change `version`, even with the key `refresh: true` it did not take the change.
