### ISSUE TITLE
Can be used with matrix strategy?

### ISSUE THREAD

**Issue by danielTobon43** [awalsh128/cache-apt-pkgs-action#38]
Hi,

I have setup my workflow where I have 

```
strategy:
      matrix:
        version: ['${{ toJSON(github.ref) }}', latest]
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install PCL
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libpcl-dev
          version: 1.0
```

and I want to cache the `libpcl-dev` for both jobs, but it seems that one is canceling the other:

![dd](https://user-images.githubusercontent.com/35694200/181996957-60461ae4-535a-4b93-a16c-20452c7894c6.png)

![dd2](https://user-images.githubusercontent.com/35694200/181997029-7d64f693-5996-4823-9940-830fd79b72da.png)
