### ISSUE TITLE
Failed to restore arm-none-eabi packages

### ISSUE THREAD

**Issue by Blank517** [awalsh128/cache-apt-pkgs-action#62]
[Workflow Actions](https://github.com/Blank517/Pokemon-UniTn/actions)
I'm trying to cache and restore those packages:
- gcc-arm-none-eabi
- binutils-arm-none-eabi

As you can see the first run builds without problems but the second one miss the headers like string.h

**Comment by awalsh128** [comment]
Hi, this is most likely related to installation scripts that aren't executed again when the cache is restored. I added a new experimental feature to do this after a restore. This is still in dev. Let me know if it resolves the issue for you.

```yaml
uses: awalsh128/cache-apt-pkgs-action@dev
with:
    packages: yourpackage
    version: 1
    execute_install_scripts: true
```
