### ISSUE TITLE
Doesn't work on custom containers ubuntu18:04

### ISSUE THREAD

**Issue by ghost** [awalsh128/cache-apt-pkgs-action#71]
Hello,
I'm unable to make this project working when using a custom container.
Here is an example yaml file:
```yaml
name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    steps:
    - name: Install packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: ca-certificates build-essential
        version: 1.0
```

And here is the error:
```
Run awalsh128/cache-apt-pkgs-action@latest
  with:
    packages: ca-certificates build-essential
    version: 1
    refresh: false
Run /home/runner/work/_actions/awalsh128/cache-apt-pkgs-action/latest/pre_cache_action.sh \
  /home/runner/work/_actions/awalsh128/cache-apt-pkgs-action/latest/pre_cache_action.sh \
    ~/cache-apt-pkgs \
    "1" \
    ca-certificates build-essential
  echo "CACHE_KEY=$(cat ~/cache-apt-pkgs/cache_key.md5)" >> $GITHUB_ENV
  shell: bash --noprofile --norc -e -o pipefail {0}
/__w/_temp/4a9fd062-d58a-4c3d-ab50-128748bc2e9c.sh: line 2: /home/runner/work/_actions/awalsh128/cache-apt-pkgs-action/latest/pre_cache_action.sh: No such file or directory
Error: Process completed with exit code 127.
```

Could you help me in making it work with a custom container?
Thank you.

**Comment by awalsh128** [comment]
Does this work on another configuration? Also, can you try with an older release?

**Comment by emiliencartesoft** [comment]
Thank you for your reply.
What do you mean by "other configuration"? I'll try with an older release.

**Comment by emiliencartesoft** [comment]
I've tried with [1.0.1](https://github.com/awalsh128/cache-apt-pkgs-action/releases/tag/v1.0.1) but same issue.

**Comment by awalsh128** [comment]
Can you share your workflow file and the full log as well? Also, can you tell me more about this custom container setup?

**Comment by emiliencartesoft** [comment]
Thank you for the reply.

Unfortunately I can't disclose the rest of the workflow file, but I made a test repository here: https://github.com/emiliencartesoft/test-apt-cache/actions

As you can see the full logs are here: https://github.com/emiliencartesoft/test-apt-cache/actions/runs/3581373128/jobs/6024358104

**Comment by awalsh128** [comment]
Nice find. I updated the dev branch with the workaround so you can use that as `@dev`. From the history I am not confident they will commit the fix soon (although it looks close to resolution). I may just issue a patch for this. Thoughts?

**Comment by emiliencartesoft** [comment]
Well it works with the example packages (ca-certificates build-essential) and when `sudo curl wget` are installed too.

I did test with other packages like `python3-pip awscli` but that didn't work for some unknown reasons: https://github.com/emiliencartesoft/test-apt-cache/actions/runs/3581841036/jobs/6025366907

Anyway with the commit https://github.com/awalsh128/cache-apt-pkgs-action/commit/343fbfd3e2ea38dcf782b2e71731a36c7d32c033 it works in custom containers, at least when `sudo curl wget` packages are installed.

**Comment by awalsh128** [comment]
Sorry for the lag here. 

RE: Action path - [Looks like this was mentioned before.](https://github.com/actions/runner/issues/716#issuecomment-795238933)
RE: Container specific - [There was a mention where the container needed to be run as priveleged](https://github.com/awalsh128/cache-apt-pkgs-action/issues/72#issuecomment-1340380290)

Let me know if the situation changes make the container option modification.

**Comment by emiliencartesoft** [comment]
Well for me the changes in the commit https://github.com/awalsh128/cache-apt-pkgs-action/commit/343fbfd3e2ea38dcf782b2e71731a36c7d32c033 should be merged into the master branch because it fixes the issue with custom containers.

**Comment by awalsh128** [comment]
I agree. I am going to put in that change as well and issue a patch. I meant the container specific one but I think I misunderstood and this solved it completely for you.

**Comment by awalsh128** [comment]
Going to assume this worked and close out this issue since it has been awhile.

**Comment by joaoantoniocardoso** [comment]
Sorry, but it doesn't seem to be working. Here's an [example](https://github.com/joaoantoniocardoso/mavlink-camera-manager/actions/runs/9134883650/job/25121294813):

```yaml
name: Test webrtc thread leak

on: [push, pull_request]

jobs:
  test-webrtc-thread-leak:
    runs-on: ubuntu-22.04
    container: ubuntu:24.04
    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
    - name: Install build dependencies
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: libunwind-dev

    - name: Checkout
      uses: actions/checkout@v4
```

output:

```bash
Run awalsh128/cache-apt-pkgs-action@v1
  with:
    packages: libunwind-dev
    execute_install_scripts: false
    debug: false
  env:
    DEBIAN_FRONTEND: noninteractive
Run ${GITHUB_ACTION_PATH}/pre_cache_action.sh \
  ${GITHUB_ACTION_PATH}/pre_cache_action.sh \
    ~/cache-apt-pkgs \
    "$VERSION" \
    "$EXEC_INSTALL_SCRIPTS" \
    "$DEBUG" \
    "$PACKAGES"
  echo "CACHE_KEY=$(cat ~/cache-apt-pkgs/cache_key.md5)" >> $GITHUB_ENV
  shell: bash --noprofile --norc -e -o pipefail {0}
  env:
    DEBIAN_FRONTEND: noninteractive
    VERSION: 
    EXEC_INSTALL_SCRIPTS: false
    DEBUG: false
    PACKAGES: libunwind-dev
22:06:54.398 Normalizing package list...
22:06:54.426 done
22:06:54.428 Validating action arguments (version='', packages='')...
22:06:54.430 aborted
22:06:54.431 Packages argument cannot be empty.
Error: Process completed with exit code 3.
```
