### ISSUE TITLE
ffmpeg can't load LibVorbis shared library

### ISSUE THREAD

**Issue by eddierubeiz** [awalsh128/cache-apt-pkgs-action#73]
Hi there,

I wanted to report a problem loading the LibVorbis shared library (details below.) Thanks for taking a look. Happy to try and provide more details as needed.

Our `cache-apt-pkgs-action` config was:

```yml
        - name: Install apt dependencies
          uses: awalsh128/cache-apt-pkgs-action@latest
          with:
            packages: libvips-tools ffmpeg mediainfo poppler-utils
            version: 1.0
```
(See https://github.com/sciencehistory/scihist_digicoll/commit/4a4d80f51bca6db3a56010a7bd4c860cb369e2a9 )

The problem looks like this:

```bash

Running `ffmpeg -y -i /tmp/shrine20221130-3705-db66qh.flac -ac 1 -codec:a aac -b:a 64k /tmp/temp_deriv20221130-3705-e1b0o7.m4a` failed with
         exit status: 127
         stdout: Nothing written
         stderr: ffmpeg: error while loading shared libraries: libvorbis.so.0: cannot open shared object file: No such file or directory
     # ./app/uploaders/asset_uploader.rb:103:in `block in <class:AssetUploader>'
     # ./spec/models/asset/derivatives_spec.rb:45:in `block (4 levels) in <main>'

```
