### ISSUE TITLE
Suggestion: Add support for third-party PPA

### ISSUE THREAD

**Issue by fambon** [awalsh128/cache-apt-pkgs-action#74]
It would be cool to be able to specify third-party PPAs as package sources in addition to the default sources.

Use case: installing (and caching) the chromium package (*not* the _official_ snap one, some plain .deb)

This use-case requires:
- sudo add-apt-repository ppa:`<some ramdom ppa repo>`
- sudo apt update
- sudo apt install chromium-browser

I guess that simply providing an additional "with" parameter `add-repository: <repository>` would be enough
and the action would then issue the relevant pre-flight commands cf above prior to the apt install

**Comment by fambon** [comment]
Eventually, I added a step to my workflow, just before the apt-cache action :-)
that step simply adds the ppa, and all goes fine:
installed package is that of the ppa, and cached.

```
    steps:
      - uses: actions/checkout@v1
      - run:|
          sudo add-apt-repository ppa:saiarcot895/chromium-beta
          sudo apt-get update
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: chromium-chromedriver postgresql postgresql-contrib
          version: 1.0

      - run: make tests
        [...]
```
