### ISSUE TITLE
Cache as root?

### ISSUE THREAD

**Issue by gamecss** [awalsh128/cache-apt-pkgs-action#80]
[There](https://github.com/gamecss/android_device_sprd_c10/actions/runs/3805957563/jobs/6474336696) is a failed action. It said 'tar: etc/default/cacerts: Cannot open: Permission denied'.
So, sudo?

**Comment by gamecss** [comment]
```
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev libwxgtk3.0-dev python3 openjdk-8-jdk mingw-w64
          version: 1.0
```
