### ISSUE TITLE
Error with multiline packages using black scalar styles `>` and `|` in YAML.

### ISSUE THREAD

**Issue by einverne** [awalsh128/cache-apt-pkgs-action#84]
```
      - name: Install dependencies for Ubuntu
        if: matrix.os == 'ubuntu-latest'
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: >
            libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev
            libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
          version: 1.0
```

Error log:

```
For more detailed logs during the artifact upload process, enable step-debugging: https://docs.github.com/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging
Error: Artifact name is not valid: cache-apt-pkgs-logs%libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
%1. Contains the following character:  Line feed \n
          
Invalid characters include:  Double quote ", Colon :, Less than <, Greater than >, Vertical bar |, Asterisk *, Question mark ?, Carriage return \r, Line feed \n, Backslash \, Forward slash /
          
These characters are not allowed in the artifact name due to limitations with certain file systems such as NTFS. To maintain file system agnostic behavior, these characters are intentionally not allowed to prevent potential problems with downloads on different file systems.
```

Version: 1.2.2 lastest

GitHub Actions can use the `Folded Block Scalar` syntax. But It seems failed in the latest version.
