### ISSUE TITLE
Debug input param doesn't disable/enable properly.

### ISSUE THREAD

**Issue by ButterscotchV** [awalsh128/cache-apt-pkgs-action#86]
The workflow file related to this issue can be found at https://github.com/SlimeVR/SlimeVR-Server/actions/runs/3911317186/workflow
This workflow is being run on the `ubuntu-20.04` container with `awalsh128/cache-apt-pkgs-action@latest`.

I'm unsure what the cause of this is, but you can see it at:
- https://github.com/SlimeVR/SlimeVR-Server/actions/runs/3911317186/jobs/6684568918#step:3:50
  - The variables are expressed as:
    ```yml
    "true" \
    "true" \
    "false" \
    libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
    ```
    corresponding to [this part of the action.yml file](https://github.com/awalsh128/cache-apt-pkgs-action/blob/master/action.yml#L48):
    ```yml
    "${{ inputs.version }}" \
    "${{ inputs.execute_install_scripts }}" \
    "${{ inputs.debug }}" \
    ${{ inputs.packages }}
    ```
    and you can see the actual values of the variables set [here in the workflow file](https://github.com/SlimeVR/SlimeVR-Server/actions/runs/3911317186/workflow#L41):
    ```yml
    packages: libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
    # Increment to invalidate the cache
    version: 1.0
    # Enables a workaround to attempt to run pre and post install scripts
    execute_install_scripts: true
    # Disables uploading logs as a build artifact
    debug: false
    ```
- https://github.com/SlimeVR/SlimeVR-Server/actions/runs/3911317186/jobs/6684568918#step:3:422
  - The debug logs artifact is uploaded even though `debug: false` is set in [the workflow file](https://github.com/SlimeVR/SlimeVR-Server/actions/runs/3911317186/workflow#L47) explicitly, and is even false by default in this action. You can note in my first bullet that the corresponding value for `debug` seems to be printed as `true`?
