### ISSUE TITLE
Multiline string for packages breaks everything

### ISSUE THREAD

**Issue by panzi** [awalsh128/cache-apt-pkgs-action#88]
If you have a lot of packages and use a multiline string for the packages parameter the setup fails, because bash attempts top run the second line as a command.

Instead of directly using the GitHub action variable interpolation you should pass the parameters as environment variables in order to prevent breakage (and command injection):

```yaml
runs:
  using: "composite"
  steps:
    - id: pre-cache
      run: |
        ${GITHUB_ACTION_PATH}/pre_cache_action.sh \
          ~/cache-apt-pkgs \
          "$VERSION" \
          "$EXEC_INSTALL_SCRIPTS" \
          "$DEBUG" \
          "$PACKAGES"
        echo "CACHE_KEY=$(cat ~/cache-apt-pkgs/cache_key.md5)" >> $GITHUB_ENV
      shell: bash
      env:
         VERSION: "${{ inputs.version }}"
         EXEC_INSTALL_SCRIPTS: "${{ inputs.execute_install_scripts }}"
         DEBUG: "${{ inputs.debug }}"
         PACKAGES: "${{ inputs.packages }}"
```

Change here:
https://github.com/awalsh128/cache-apt-pkgs-action/blob/9b2b4f2004c400ca4db1cd3622055dd784244fcb/action.yml#L44-L52
https://github.com/awalsh128/cache-apt-pkgs-action/blob/9b2b4f2004c400ca4db1cd3622055dd784244fcb/action.yml#L61-L73

Note that simply adding " " around `${{ inputs.packages }}` in the run command will still allow command injection if someone uses a " in the packages parameter. So using env vars is cleaner.

However, this then passes the packages as a single parameter, but since you then do this anyway it shouldn't matter (in fact make that simpler, since you merge it into a single string anyway):
https://github.com/awalsh128/cache-apt-pkgs-action/blob/9b2b4f2004c400ca4db1cd3622055dd784244fcb/pre_cache_action.sh#L28-L31
https://github.com/awalsh128/cache-apt-pkgs-action/blob/9b2b4f2004c400ca4db1cd3622055dd784244fcb/post_cache_action.sh#L29-L35
https://github.com/awalsh128/cache-apt-pkgs-action/blob/9b2b4f2004c400ca4db1cd3622055dd784244fcb/install_and_cache_pkgs.sh#L19-L22
